Gon 16(공동구매 생성)
gong9ri/gong9ri pull request #28
Opened 2023-07-05 07:20 UTC by KimWonhee626

- 상품 detail 페이지에서 총대되기 버튼 클릭하면 공동구매 생성
- 상품과 연결된 공동구매 중 상태가 'PROGRESS'인 공동구매가 있는 경우 생성 안됨
- 공동구매 list 페이지에서 조회
- 공동구매 detail 페이지에서 공동구매 참여하기 버튼을 통해 참여 가능
- 이미 공동구매에 참여중인 사용자는 참여 불가

[추가 구현할 것]
- 진행중인 공동구매 있으면 총대되기 버튼 -> 공동구매 바로가기 버튼으로 바뀌도록
- 시간 만료되면 공동구매 status 수정 후 참여 제한
- 남은시간 표기(?)

2023-07-05 09:31 UTC, uoise requested changes

2023-07-05 09:31 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/groupBuy/service/GroupBuyMemberService.java
> +		List<GroupBuyMember> groupBuyMembers = groupBuyMemberRepository.findAllByGroupBuyId(groupBuy.getId());
총대를 멜때 `List<GroupBuyMember>` 가 empty 가 아닌 경우가 있나요?

2023-07-05 09:31 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/groupBuy/service/GroupBuyMemberService.java
> +		groupBuyMemberRepository.saveAll(groupBuyMembers);
`saveAll()` 로 사용했을때 `@LastModifiedDate` 가 갱신되는지 확인해보셨나요?
`groupBuyMember`를 만들고 난 후 `findAllByGroupBuyId()` 해도 될 것 같아요

2023-07-05 09:31 UTC, uoise commented on src/main/resources/templates/groupBuy/detail.html
> +                <div th:text="${groupBuy.name}"></div>
공동구매 명으로 하거나 `groupBuy.product.name` 을 써야 할 것 같아요

2023-07-05 09:31 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/service/ProductService.java
> +        return product.getGroupBuys().stream()
`product` 에 `groupBuys` 필드가 있는 것 같은데, 그 부분을 없애고
`Boolean existsByProductIdAndGroupBuyStatus(final Long productId, final String status);` 만드셔서
`existsByProductIdAndGroupBuyStatus(product.getId(), GroupBuyStatus.PROGRESS.getValue())` 
로 검증하셔야 합니다

2023-07-09 01:22 UTC, uoise approved these changes

2023-07-09 04:37 UTC, debussykim approved these changes

2023-07-09 04:37 UTC, merged

2023-07-09 04:38 UTC, kkambbak approved these changes