GON-6(상품 등록)
gong9ri/gong9ri pull request #8
Opened 2023-06-27 05:01 UTC by havegrit

상품 등록 기능 구현 완료했습니다.

다음으로 상품 조회(GON-7) 기능 구현 작업 진행할 예정입니다.

2023-06-27 05:23 UTC, uoise requested changes

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/controller/ProductController.java
> +@RequestMapping("/store/product")
/store/product 보다 /product로 관리해도 좋아보이는데 어떠신가요?

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/dto/ProductDTO.java
> +    @NotBlank
Integer에 @NotBlank 보다는 @NotNull 이 적절해보입니다

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/dto/ProductDTO.java
> +    private List<ProductImage> images;
ImageDTO 도 필요해보입니다

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/entity/Product.java
> +	public void addProductOption(ProductOption productOption) {
여러개를 추가하는 메소드도 있으면 좋을것 같아요

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/entity/ProductOption.java
> +    private Product product;
Product에 setter가 있는 이유가 궁금합니다

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/service/ProductService.java
> +    public RsData<Product> registerProduct(final ProductDTO productDTO) {
ProductDTO 에 `public Product of() {}` 메소드로 처리해도 좋아보입니다

2023-06-27 05:23 UTC, uoise commented on src/main/java/com/ll/gong9ri/boundedContext/product/service/ProductService.java
> +        productDTO.getOptionOneDetails().stream().flatMap(optionOneDetail ->
OptionOne 이나 OptionTwo 가 nullable 인데 이때도 flatMap이 작동하나요?

2023-06-27 05:35 UTC, havegrit commented on src/main/java/com/ll/gong9ri/boundedContext/product/dto/ProductDTO.java
> +    @NotBlank
네 정정하겠습니다.

2023-06-27 05:36 UTC, havegrit commented on src/main/java/com/ll/gong9ri/boundedContext/product/dto/ProductDTO.java
> +    private List<ProductImage> images;
ImageDTO, 테스트할 때 쓰이지 않아서 깜빡했네요. 
추가하겠습니다.

2023-06-27 05:36 UTC, havegrit commented on src/main/java/com/ll/gong9ri/boundedContext/product/entity/Product.java
> +	public void addProductOption(ProductOption productOption) {
네 이것도 추가하겠습니다.

2023-06-27 05:48 UTC, havegrit commented on src/main/java/com/ll/gong9ri/boundedContext/product/service/ProductService.java
> +        productDTO.getOptionOneDetails().stream().flatMap(optionOneDetail ->
null일 때 에러 발생할 것 같습니다. 이 부분 핸들링 작업하겠습니다.

2023-06-27 06:05 UTC, havegrit commented on src/main/java/com/ll/gong9ri/boundedContext/product/entity/ProductOption.java
> +    private Product product;
처음 구현할 때, service에서 Product 객체 생성 시점이 ProductOption 생성 시점보다 뒤에 있어서 ProductOption 객체에 Product를 초기화 해주기위해 추가해줬던 부분인데, 지금은 Product가 ProductOption 보다 앞에 생성돼서 지워도 될 것 같습니다. 관련 부분 수정하도록 하겠습니다.

2023-06-28 04:01 UTC, uoise requested changes

2023-06-28 23:41 UTC, uoise approved these changes

2023-06-29 04:26 UTC, debussykim approved these changes

2023-06-29 05:40 UTC, merged